export { default as Error } from './Error'
export { default as Input } from './Input'
export { default as Loader } from './Loader'
export { default as SnackBar } from './SnackBar' 
export { default as GoBackButton } from './GoBackButton' 
export { default as BasicModal } from './Modal' 